[tool.poetry]
name = "netaudio"
version = "0.0.1"
description = "Control network audio devices"
authors = ["Christopher Ritsen <chris.ritsen@gmail.com>"]
license = "unlicense"

[tool.poetry.dependencies]
argcomplete = "^2.0.0"
argparse = "^1.4.0"
netifaces = "^0.11.0"
pyee = "^9.0.4"
python = "^3.9"
twisted = "^22.1.0"
zeroconf = "^0.38.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
